version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - npm install -g @angular/cli@6
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - echo "Pre-Build Stage"
  build:
    commands:
      - echo "Build Stage"
      - ng build --prod
  post_build:
    commands:
      - echo "Post-Build Stage"
artifacts:
  type: zip
  base-directory: 'dist/'
  discard-paths: yes
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
