version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - echo "Pre-Build Stage"
      - ng build --prod
  build:
    commands:
      - echo "Build Stage"
      - ng serve --prod
  post_build:
    commands:
      - echo "Post-Build Stage"
      -
artifacts:
  type: zip
